[2024-12-01T02:03:52.983+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_table.create_table manual__2024-12-01T02:03:47.843706+00:00 [queued]>
[2024-12-01T02:03:52.996+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_table.create_table manual__2024-12-01T02:03:47.843706+00:00 [queued]>
[2024-12-01T02:03:52.997+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-12-01T02:03:53.017+0000] {taskinstance.py:2191} INFO - Executing <Task(PostgresOperator): create_table> on 2024-12-01 02:03:47.843706+00:00
[2024-12-01T02:03:53.026+0000] {standard_task_runner.py:60} INFO - Started process 307 to run task
[2024-12-01T02:03:53.030+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'create_table', 'create_table', 'manual__2024-12-01T02:03:47.843706+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/create_table.py', '--cfg-path', '/tmp/tmpl5mkseop']
[2024-12-01T02:03:53.033+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask create_table
[2024-12-01T02:03:53.048+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-01T02:03:53.103+0000] {task_command.py:423} INFO - Running <TaskInstance: create_table.create_table manual__2024-12-01T02:03:47.843706+00:00 [running]> on host d047790ecdd5
[2024-12-01T02:03:53.228+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='create_table' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-12-01T02:03:47.843706+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-01T02:03:47.843706+00:00'
[2024-12-01T02:03:53.231+0000] {sql.py:276} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS customer (
            id UUID PRIMARY KEY,
            lastname VARCHAR NOT NULL,
            firstname VARCHAR NOT NULL,
            sex VARCHAR NOT NULL,
            street_number SMALLINT NOT NULL,
            street_name VARCHAR NOT NULL,
            city VARCHAR NOT NULL,
            postcode VARCHAR NOT NULL,
            region VARCHAR NOT NULL,
            modification_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
       
[2024-12-01T02:03:53.245+0000] {base.py:83} INFO - Using connection ID 'postgres' for task execution.
[2024-12-01T02:03:53.263+0000] {base.py:83} INFO - Using connection ID 'postgres' for task execution.
[2024-12-01T02:03:53.268+0000] {sql.py:450} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS customer (
            id UUID PRIMARY KEY,
            lastname VARCHAR NOT NULL,
            firstname VARCHAR NOT NULL,
            sex VARCHAR NOT NULL,
            street_number SMALLINT NOT NULL,
            street_name VARCHAR NOT NULL,
            city VARCHAR NOT NULL,
            postcode VARCHAR NOT NULL,
            region VARCHAR NOT NULL,
            modification_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
       , parameters: None
[2024-12-01T02:03:53.293+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=create_table, task_id=create_table, execution_date=20241201T020347, start_date=20241201T020352, end_date=20241201T020353
[2024-12-01T02:03:53.323+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-12-01T02:03:53.347+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
