[2024-12-01T02:36:54.705+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: init_order.create_table_order manual__2024-12-01T02:36:44.649919+00:00 [queued]>
[2024-12-01T02:36:54.716+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: init_order.create_table_order manual__2024-12-01T02:36:44.649919+00:00 [queued]>
[2024-12-01T02:36:54.716+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-12-01T02:36:54.734+0000] {taskinstance.py:2191} INFO - Executing <Task(PostgresOperator): create_table_order> on 2024-12-01 02:36:44.649919+00:00
[2024-12-01T02:36:54.742+0000] {standard_task_runner.py:60} INFO - Started process 1462 to run task
[2024-12-01T02:36:54.745+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'init_order', 'create_table_order', 'manual__2024-12-01T02:36:44.649919+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/init_order.py', '--cfg-path', '/tmp/tmphspanq6d']
[2024-12-01T02:36:54.748+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask create_table_order
[2024-12-01T02:36:54.763+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-01T02:36:54.809+0000] {task_command.py:423} INFO - Running <TaskInstance: init_order.create_table_order manual__2024-12-01T02:36:44.649919+00:00 [running]> on host d047790ecdd5
[2024-12-01T02:36:54.927+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='init_order' AIRFLOW_CTX_TASK_ID='create_table_order' AIRFLOW_CTX_EXECUTION_DATE='2024-12-01T02:36:44.649919+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-01T02:36:44.649919+00:00'
[2024-12-01T02:36:54.929+0000] {sql.py:276} INFO - Executing: CREATE TABLE IF NOT EXISTS "order" (
  id UUID,
  date_order TIMESTAMP,
  date_shipping TIMESTAMP,
  quantity SMALLINT,
  price REAL,
  customer_id UUID REFERENCES customer(id),
  product_id UUID REFERENCES product(id)
);
[2024-12-01T02:36:54.939+0000] {base.py:83} INFO - Using connection ID 'postgres' for task execution.
[2024-12-01T02:36:54.951+0000] {base.py:83} INFO - Using connection ID 'postgres' for task execution.
[2024-12-01T02:36:54.955+0000] {sql.py:450} INFO - Running statement: CREATE TABLE IF NOT EXISTS "order" (
  id UUID,
  date_order TIMESTAMP,
  date_shipping TIMESTAMP,
  quantity SMALLINT,
  price REAL,
  customer_id UUID REFERENCES customer(id),
  product_id UUID REFERENCES product(id)
);, parameters: None
[2024-12-01T02:36:54.972+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=init_order, task_id=create_table_order, execution_date=20241201T023644, start_date=20241201T023654, end_date=20241201T023654
[2024-12-01T02:36:54.998+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-12-01T02:36:55.020+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
