[2024-12-01T02:36:51.865+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: init_order.create_table_customer manual__2024-12-01T02:36:44.649919+00:00 [queued]>
[2024-12-01T02:36:51.900+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: init_order.create_table_customer manual__2024-12-01T02:36:44.649919+00:00 [queued]>
[2024-12-01T02:36:51.902+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-12-01T02:36:51.947+0000] {taskinstance.py:2191} INFO - Executing <Task(PostgresOperator): create_table_customer> on 2024-12-01 02:36:44.649919+00:00
[2024-12-01T02:36:51.969+0000] {standard_task_runner.py:60} INFO - Started process 1458 to run task
[2024-12-01T02:36:51.977+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'init_order', 'create_table_customer', 'manual__2024-12-01T02:36:44.649919+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/init_order.py', '--cfg-path', '/tmp/tmpx6dlr6nf']
[2024-12-01T02:36:51.981+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask create_table_customer
[2024-12-01T02:36:52.022+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-01T02:36:52.113+0000] {task_command.py:423} INFO - Running <TaskInstance: init_order.create_table_customer manual__2024-12-01T02:36:44.649919+00:00 [running]> on host d047790ecdd5
[2024-12-01T02:36:52.388+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='init_order' AIRFLOW_CTX_TASK_ID='create_table_customer' AIRFLOW_CTX_EXECUTION_DATE='2024-12-01T02:36:44.649919+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-01T02:36:44.649919+00:00'
[2024-12-01T02:36:52.391+0000] {sql.py:276} INFO - Executing: CREATE TABLE IF NOT EXISTS customer (
  id UUID PRIMARY KEY,
  lastname VARCHAR,
  firstname VARCHAR,
  sex VARCHAR,
  street_number SMALLINT,
  street_name VARCHAR,
  city VARCHAR,
  postcode VARCHAR,
  region VARCHAR,
  modification_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
[2024-12-01T02:36:52.424+0000] {base.py:83} INFO - Using connection ID 'postgres' for task execution.
[2024-12-01T02:36:52.443+0000] {base.py:83} INFO - Using connection ID 'postgres' for task execution.
[2024-12-01T02:36:52.475+0000] {sql.py:450} INFO - Running statement: CREATE TABLE IF NOT EXISTS customer (
  id UUID PRIMARY KEY,
  lastname VARCHAR,
  firstname VARCHAR,
  sex VARCHAR,
  street_number SMALLINT,
  street_name VARCHAR,
  city VARCHAR,
  postcode VARCHAR,
  region VARCHAR,
  modification_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);, parameters: None
[2024-12-01T02:36:52.518+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=init_order, task_id=create_table_customer, execution_date=20241201T023644, start_date=20241201T023651, end_date=20241201T023652
[2024-12-01T02:36:52.566+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-12-01T02:36:52.654+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
