[2024-12-01T02:07:55.575+0000] {processor.py:161} INFO - Started process (PID=1416) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:07:55.576+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:07:55.579+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:07:55.579+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:07:55.604+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:07:55.625+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.054 seconds
[2024-12-01T02:08:15.948+0000] {processor.py:161} INFO - Started process (PID=1477) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:08:15.949+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:08:15.952+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:08:15.951+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:08:15.956+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:08:15.955+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 53
    create_postgres_conn = PythonOperator(
    ^
IndentationError: expected an indented block
[2024-12-01T02:08:15.956+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:08:15.987+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.043 seconds
[2024-12-01T02:08:32.879+0000] {processor.py:161} INFO - Started process (PID=1494) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:08:32.880+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:08:32.883+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:08:32.883+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:08:32.908+0000] {processor.py:840} INFO - DAG(s) 'init_order' retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:08:33.141+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:08:33.140+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:init_order
[2024-12-01T02:08:33.163+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:08:33.162+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:init_order
[2024-12-01T02:08:33.174+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:08:33.174+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:init_order
[2024-12-01T02:08:33.175+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:08:33.174+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-12-01T02:08:33.192+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:08:33.192+0000] {dag.py:3058} INFO - Creating ORM DAG for init_order
[2024-12-01T02:08:33.209+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:08:33.208+0000] {dag.py:3823} INFO - Setting next_dagrun for init_order to 2024-12-01 00:01:00+00:00, run_after=2024-12-02 00:01:00+00:00
[2024-12-01T02:08:33.239+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.366 seconds
[2024-12-01T02:09:03.282+0000] {processor.py:161} INFO - Started process (PID=1562) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:09:03.284+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:09:03.287+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:09:03.287+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:09:03.318+0000] {processor.py:840} INFO - DAG(s) 'init_order' retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:09:03.351+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:09:03.350+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-12-01T02:09:03.392+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:09:03.392+0000] {dag.py:3823} INFO - Setting next_dagrun for init_order to 2024-12-01 00:01:00+00:00, run_after=2024-12-02 00:01:00+00:00
[2024-12-01T02:09:03.419+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.141 seconds
[2024-12-01T02:09:33.636+0000] {processor.py:161} INFO - Started process (PID=1635) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:09:33.637+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:09:33.639+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:09:33.639+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:09:33.671+0000] {processor.py:840} INFO - DAG(s) 'init_order' retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:09:33.702+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:09:33.702+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-12-01T02:09:33.744+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:09:33.744+0000] {dag.py:3823} INFO - Setting next_dagrun for init_order to 2024-12-01 00:01:00+00:00, run_after=2024-12-02 00:01:00+00:00
[2024-12-01T02:09:33.773+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.144 seconds
[2024-12-01T02:10:03.857+0000] {processor.py:161} INFO - Started process (PID=1704) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:10:03.858+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:10:03.862+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:10:03.860+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:10:03.891+0000] {processor.py:840} INFO - DAG(s) 'init_order' retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:10:03.921+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:10:03.921+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-12-01T02:10:03.960+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:10:03.959+0000] {dag.py:3823} INFO - Setting next_dagrun for init_order to 2024-12-01 00:01:00+00:00, run_after=2024-12-02 00:01:00+00:00
[2024-12-01T02:10:03.988+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.136 seconds
[2024-12-01T02:10:34.474+0000] {processor.py:161} INFO - Started process (PID=1772) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:10:34.475+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:10:34.477+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:10:34.477+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:10:34.501+0000] {processor.py:840} INFO - DAG(s) 'init_order' retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:10:34.533+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:10:34.533+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-12-01T02:10:34.576+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:10:34.575+0000] {dag.py:3823} INFO - Setting next_dagrun for init_order to 2024-12-01 00:01:00+00:00, run_after=2024-12-02 00:01:00+00:00
[2024-12-01T02:10:34.604+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.134 seconds
[2024-12-01T02:11:04.813+0000] {processor.py:161} INFO - Started process (PID=1840) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:11:04.814+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:11:04.816+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:11:04.816+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:11:04.839+0000] {processor.py:840} INFO - DAG(s) 'init_order' retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:11:04.872+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:11:04.872+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-12-01T02:11:04.911+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:11:04.910+0000] {dag.py:3823} INFO - Setting next_dagrun for init_order to 2024-12-01 00:01:00+00:00, run_after=2024-12-02 00:01:00+00:00
[2024-12-01T02:11:04.941+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.132 seconds
[2024-12-01T02:11:14.259+0000] {processor.py:161} INFO - Started process (PID=1870) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:11:14.260+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:11:14.262+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:11:14.262+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:11:14.265+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:11:14.264+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:11:14.266+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:11:14.294+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.041 seconds
[2024-12-01T02:11:44.552+0000] {processor.py:161} INFO - Started process (PID=1935) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:11:44.553+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:11:44.556+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:11:44.555+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:11:44.560+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:11:44.559+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:11:44.560+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:11:44.593+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.046 seconds
[2024-12-01T02:12:14.635+0000] {processor.py:161} INFO - Started process (PID=1996) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:12:14.645+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:12:14.649+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:12:14.648+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:12:14.655+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:12:14.653+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:12:14.655+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:12:14.699+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.071 seconds
[2024-12-01T02:12:44.856+0000] {processor.py:161} INFO - Started process (PID=2064) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:12:44.857+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:12:44.860+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:12:44.859+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:12:44.863+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:12:44.862+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:12:44.863+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:12:44.891+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.038 seconds
[2024-12-01T02:13:15.694+0000] {processor.py:161} INFO - Started process (PID=2130) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:13:15.695+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:13:15.696+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:13:15.696+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:13:15.699+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:13:15.698+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:13:15.700+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:13:15.729+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.038 seconds
[2024-12-01T02:13:46.208+0000] {processor.py:161} INFO - Started process (PID=2197) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:13:46.209+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:13:46.210+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:13:46.209+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:13:46.214+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:13:46.212+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:13:46.214+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:13:46.244+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.041 seconds
[2024-12-01T02:14:16.577+0000] {processor.py:161} INFO - Started process (PID=2274) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:14:16.578+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:14:16.580+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:14:16.579+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:14:16.584+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:14:16.583+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:14:16.585+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:14:16.622+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.052 seconds
[2024-12-01T02:14:46.830+0000] {processor.py:161} INFO - Started process (PID=2342) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:14:46.831+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:14:46.832+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:14:46.832+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:14:46.836+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:14:46.835+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:14:46.837+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:14:46.864+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.039 seconds
[2024-12-01T02:15:17.454+0000] {processor.py:161} INFO - Started process (PID=2410) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:15:17.456+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:15:17.457+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:15:17.456+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:15:17.460+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:15:17.459+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:15:17.461+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:15:17.492+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.041 seconds
[2024-12-01T02:15:47.776+0000] {processor.py:161} INFO - Started process (PID=2478) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:15:47.777+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:15:47.779+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:15:47.778+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:15:47.782+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:15:47.781+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:15:47.783+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:15:47.811+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.040 seconds
[2024-12-01T02:16:18.131+0000] {processor.py:161} INFO - Started process (PID=2545) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:16:18.132+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:16:18.133+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:16:18.133+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:16:18.137+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:16:18.136+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:16:18.137+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:16:18.164+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.037 seconds
[2024-12-01T02:16:48.275+0000] {processor.py:161} INFO - Started process (PID=2613) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:16:48.277+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:16:48.278+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:16:48.277+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:16:48.283+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:16:48.282+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:16:48.284+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:16:48.312+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.041 seconds
[2024-12-01T02:17:18.409+0000] {processor.py:161} INFO - Started process (PID=2680) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:17:18.410+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:17:18.412+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:17:18.411+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:17:18.415+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:17:18.414+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:17:18.416+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:17:18.449+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.044 seconds
[2024-12-01T02:17:49.142+0000] {processor.py:161} INFO - Started process (PID=2748) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:17:49.143+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:17:49.145+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:17:49.144+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:17:49.149+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:17:49.148+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:17:49.150+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:17:49.181+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.044 seconds
[2024-12-01T02:18:19.653+0000] {processor.py:161} INFO - Started process (PID=2817) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:18:19.654+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:18:19.655+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:18:19.655+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:18:19.660+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:18:19.659+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:18:19.660+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:18:19.686+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.038 seconds
[2024-12-01T02:18:50.553+0000] {processor.py:161} INFO - Started process (PID=2885) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:18:50.554+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:18:50.555+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:18:50.554+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:18:50.559+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:18:50.558+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:18:50.559+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:18:50.586+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.038 seconds
[2024-12-01T02:19:20.967+0000] {processor.py:161} INFO - Started process (PID=2961) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:19:20.969+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:19:20.970+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:19:20.970+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:19:20.976+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:19:20.975+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:19:20.977+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:19:21.009+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.046 seconds
[2024-12-01T02:19:51.319+0000] {processor.py:161} INFO - Started process (PID=3029) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:19:51.326+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:19:51.327+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:19:51.327+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:19:51.332+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:19:51.331+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:19:51.333+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:19:51.378+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.065 seconds
[2024-12-01T02:20:21.611+0000] {processor.py:161} INFO - Started process (PID=3097) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:20:21.613+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:20:21.615+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:20:21.615+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:20:21.621+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:20:21.620+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:20:21.621+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:20:21.650+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.044 seconds
[2024-12-01T02:20:51.818+0000] {processor.py:161} INFO - Started process (PID=3164) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:20:51.819+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:20:51.821+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:20:51.820+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:20:51.826+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:20:51.825+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:20:51.826+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:20:51.863+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.051 seconds
[2024-12-01T02:21:22.248+0000] {processor.py:161} INFO - Started process (PID=3232) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:21:22.249+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:21:22.250+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:21:22.250+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:21:22.255+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:21:22.253+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:21:22.255+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:21:22.281+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.038 seconds
[2024-12-01T02:21:52.837+0000] {processor.py:161} INFO - Started process (PID=3302) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:21:52.838+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:21:52.840+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:21:52.839+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:21:52.844+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:21:52.843+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:21:52.844+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:21:52.873+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.041 seconds
[2024-12-01T02:22:23.104+0000] {processor.py:161} INFO - Started process (PID=3370) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:22:23.105+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:22:23.106+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:22:23.106+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:22:23.110+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:22:23.109+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:22:23.110+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:22:23.136+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.036 seconds
[2024-12-01T02:22:53.214+0000] {processor.py:161} INFO - Started process (PID=3439) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:22:53.215+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:22:53.215+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:22:53.215+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:22:53.219+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:22:53.218+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:22:53.219+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:22:53.247+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.037 seconds
[2024-12-01T02:23:23.588+0000] {processor.py:161} INFO - Started process (PID=3509) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:23:23.590+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:23:23.591+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:23:23.590+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:23:23.596+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:23:23.595+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:23:23.597+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:23:23.623+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.040 seconds
[2024-12-01T02:23:54.416+0000] {processor.py:161} INFO - Started process (PID=3575) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:23:54.417+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:23:54.419+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:23:54.419+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:23:54.423+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:23:54.422+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:23:54.424+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:23:54.456+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.044 seconds
[2024-12-01T02:24:24.588+0000] {processor.py:161} INFO - Started process (PID=3651) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:24:24.590+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:24:24.591+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:24:24.590+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:24:24.596+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:24:24.595+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:24:24.596+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:24:24.648+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.065 seconds
[2024-12-01T02:24:54.739+0000] {processor.py:161} INFO - Started process (PID=3720) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:24:54.740+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:24:54.741+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:24:54.741+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:24:54.745+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:24:54.744+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:24:54.746+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:24:54.802+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.068 seconds
[2024-12-01T02:25:25.024+0000] {processor.py:161} INFO - Started process (PID=3786) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:25:25.027+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:25:25.029+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:25:25.028+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:25:25.034+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:25:25.033+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:25:25.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:25:25.074+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.057 seconds
[2024-12-01T02:25:55.327+0000] {processor.py:161} INFO - Started process (PID=3854) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:25:55.328+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:25:55.329+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:25:55.329+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:25:55.334+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:25:55.332+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:25:55.334+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:25:55.398+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.086 seconds
[2024-12-01T02:26:26.239+0000] {processor.py:161} INFO - Started process (PID=3921) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:26:26.241+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:26:26.242+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:26:26.242+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:26:26.250+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:26:26.247+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:26:26.251+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:26:26.334+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.100 seconds
[2024-12-01T02:26:56.792+0000] {processor.py:161} INFO - Started process (PID=3982) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:26:56.797+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:26:56.800+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:26:56.799+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:26:56.810+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:26:56.808+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:26:56.817+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:26:56.901+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.119 seconds
[2024-12-01T02:27:27.837+0000] {processor.py:161} INFO - Started process (PID=4048) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:27:27.838+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:27:27.840+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:27:27.839+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:27:27.843+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:27:27.842+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:27:27.844+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:27:27.899+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.071 seconds
[2024-12-01T02:27:58.066+0000] {processor.py:161} INFO - Started process (PID=4116) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:27:58.068+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:27:58.069+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:27:58.068+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:27:58.072+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:27:58.071+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:27:58.073+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:27:58.109+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.047 seconds
[2024-12-01T02:28:28.470+0000] {processor.py:161} INFO - Started process (PID=4184) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:28:28.471+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:28:28.473+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:28:28.472+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:28:28.478+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:28:28.476+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:28:28.478+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:28:28.506+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.040 seconds
[2024-12-01T02:28:59.442+0000] {processor.py:161} INFO - Started process (PID=4252) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:28:59.443+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:28:59.445+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:28:59.444+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:28:59.449+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:28:59.448+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:28:59.449+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:28:59.477+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.039 seconds
[2024-12-01T02:29:30.166+0000] {processor.py:161} INFO - Started process (PID=4321) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:29:30.167+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:29:30.169+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:29:30.168+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:29:30.173+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:29:30.172+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:29:30.174+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:29:30.217+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.064 seconds
[2024-12-01T02:30:00.585+0000] {processor.py:161} INFO - Started process (PID=4389) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:30:00.587+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:30:00.588+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:30:00.588+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:30:00.593+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:30:00.591+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:30:00.594+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:30:00.621+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.043 seconds
[2024-12-01T02:30:30.824+0000] {processor.py:161} INFO - Started process (PID=4464) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:30:30.825+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:30:30.827+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:30:30.826+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:30:30.832+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:30:30.831+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:30:30.833+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:30:30.862+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.044 seconds
[2024-12-01T02:31:01.609+0000] {processor.py:161} INFO - Started process (PID=4533) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:31:01.611+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:31:01.616+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:31:01.614+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:31:01.623+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:31:01.621+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:31:01.627+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:31:01.661+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.065 seconds
[2024-12-01T02:31:32.227+0000] {processor.py:161} INFO - Started process (PID=4601) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:31:32.229+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:31:32.232+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:31:32.231+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:31:32.236+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:31:32.235+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:31:32.237+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:31:32.275+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.052 seconds
[2024-12-01T02:32:02.523+0000] {processor.py:161} INFO - Started process (PID=4670) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:32:02.524+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:32:02.526+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:32:02.525+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:32:02.530+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:32:02.529+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:32:02.531+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:32:02.569+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.050 seconds
[2024-12-01T02:32:33.050+0000] {processor.py:161} INFO - Started process (PID=4735) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:32:33.051+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:32:33.052+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:32:33.052+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:32:33.056+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:32:33.054+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:32:33.056+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:32:33.093+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.047 seconds
[2024-12-01T02:33:03.296+0000] {processor.py:161} INFO - Started process (PID=4803) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:33:03.297+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:33:03.298+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:33:03.298+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:33:03.303+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:33:03.301+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:33:03.303+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:33:03.336+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.043 seconds
[2024-12-01T02:33:33.603+0000] {processor.py:161} INFO - Started process (PID=4871) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:33:33.604+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:33:33.606+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:33:33.605+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:33:33.610+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:33:33.609+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:33:33.610+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:33:33.639+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.040 seconds
[2024-12-01T02:34:04.459+0000] {processor.py:161} INFO - Started process (PID=4939) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:34:04.460+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:34:04.461+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:34:04.461+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:34:04.465+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:34:04.464+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:34:04.465+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:34:04.496+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.042 seconds
[2024-12-01T02:34:35.183+0000] {processor.py:161} INFO - Started process (PID=5007) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:34:35.184+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:34:35.186+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:34:35.186+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:34:35.191+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:34:35.190+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:34:35.192+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:34:35.225+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.047 seconds
[2024-12-01T02:35:05.728+0000] {processor.py:161} INFO - Started process (PID=5083) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:35:05.729+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:35:05.731+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:35:05.730+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:35:05.734+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:35:05.733+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:35:05.735+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:35:05.768+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.045 seconds
[2024-12-01T02:35:36.216+0000] {processor.py:161} INFO - Started process (PID=5152) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:35:36.218+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:35:36.221+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:35:36.219+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:35:36.237+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:35:36.235+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:35:36.238+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:35:36.289+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.077 seconds
[2024-12-01T02:36:07.295+0000] {processor.py:161} INFO - Started process (PID=5220) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:36:07.296+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:36:07.297+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:36:07.297+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:36:07.301+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:36:07.300+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/init_order.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/init_order.py", line 39
    else:
    ^
SyntaxError: invalid syntax
[2024-12-01T02:36:07.302+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:36:07.345+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.055 seconds
[2024-12-01T02:36:33.519+0000] {processor.py:161} INFO - Started process (PID=5286) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:36:33.520+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:36:33.521+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:36:33.521+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:36:33.553+0000] {processor.py:840} INFO - DAG(s) 'init_order' retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:36:33.708+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:36:33.708+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-12-01T02:36:33.744+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:36:33.744+0000] {dag.py:3823} INFO - Setting next_dagrun for init_order to 2024-12-01 00:01:00+00:00, run_after=2024-12-02 00:01:00+00:00
[2024-12-01T02:36:33.784+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.270 seconds
[2024-12-01T02:37:04.386+0000] {processor.py:161} INFO - Started process (PID=5361) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:37:04.387+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:37:04.388+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:37:04.388+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:37:04.425+0000] {processor.py:840} INFO - DAG(s) 'init_order' retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:37:04.457+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:37:04.457+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-12-01T02:37:04.495+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:37:04.494+0000] {dag.py:3823} INFO - Setting next_dagrun for init_order to 2024-12-01 00:01:00+00:00, run_after=2024-12-02 00:01:00+00:00
[2024-12-01T02:37:04.524+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.141 seconds
[2024-12-01T02:37:34.609+0000] {processor.py:161} INFO - Started process (PID=5432) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:37:34.612+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:37:34.614+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:37:34.614+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:37:34.654+0000] {processor.py:840} INFO - DAG(s) 'init_order' retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:37:34.694+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:37:34.694+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-12-01T02:37:34.741+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:37:34.740+0000] {dag.py:3823} INFO - Setting next_dagrun for init_order to 2024-12-01 00:01:00+00:00, run_after=2024-12-02 00:01:00+00:00
[2024-12-01T02:37:34.777+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.177 seconds
[2024-12-01T02:38:04.924+0000] {processor.py:161} INFO - Started process (PID=5499) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:38:04.925+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:38:04.926+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:38:04.926+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:38:04.965+0000] {processor.py:840} INFO - DAG(s) 'init_order' retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:38:05.006+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:38:05.006+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-12-01T02:38:05.045+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:38:05.045+0000] {dag.py:3823} INFO - Setting next_dagrun for init_order to 2024-12-01 00:01:00+00:00, run_after=2024-12-02 00:01:00+00:00
[2024-12-01T02:38:05.078+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.159 seconds
[2024-12-01T02:38:35.232+0000] {processor.py:161} INFO - Started process (PID=5568) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:38:35.234+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:38:35.235+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:38:35.234+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:38:35.273+0000] {processor.py:840} INFO - DAG(s) 'init_order' retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:38:35.309+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:38:35.308+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-12-01T02:38:35.349+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:38:35.349+0000] {dag.py:3823} INFO - Setting next_dagrun for init_order to 2024-12-01 00:01:00+00:00, run_after=2024-12-02 00:01:00+00:00
[2024-12-01T02:38:35.380+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.152 seconds
[2024-12-01T02:39:05.747+0000] {processor.py:161} INFO - Started process (PID=5636) to work on /opt/airflow/dags/init_order.py
[2024-12-01T02:39:05.748+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/init_order.py for tasks to queue
[2024-12-01T02:39:05.750+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:39:05.750+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/init_order.py
[2024-12-01T02:39:05.789+0000] {processor.py:840} INFO - DAG(s) 'init_order' retrieved from /opt/airflow/dags/init_order.py
[2024-12-01T02:39:05.820+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:39:05.820+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-12-01T02:39:05.857+0000] {logging_mixin.py:188} INFO - [2024-12-01T02:39:05.857+0000] {dag.py:3823} INFO - Setting next_dagrun for init_order to 2024-12-01 00:01:00+00:00, run_after=2024-12-02 00:01:00+00:00
[2024-12-01T02:39:05.894+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/init_order.py took 0.153 seconds
